### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ghost** [dnault/xml-patch#1]
There's no xml-patch-<version>.jar file.

**Comment by dnault** [comment]
Thanks, I'll update the readme.

The JAR is available from the JCenter Maven repository:
    https://jcenter.bintray.com/com/github/dnault/xml-patch/0.1.0/xml-patch-0.1.0.jar

Additional JARs required (unless you're using a dependency manager like Gradle, Ivy, Maven, etc.):

```
jdom 1.1.3
jaxen 1.1.6
commons-io 2.4
jopt-simple 4.8
```

**Comment by ghost** [comment]
Now it works :) Thanks!
BTW is there any tool to generate xml pach in RFC5162 format?

**Comment by dnault** [comment]
Such a tool may exist, but I'm not aware of it. If you find one, let me know and I'll include a link to it in the documentation.
