### ISSUE TITLE
Allow "patch" root element in accordance with RFC 7351

### ISSUE THREAD

**Issue by jbuhacoff** [dnault/xml-patch#2]
Patcher.java line 48 requires the root element of the patch file to be "diff" as shown in the README

RFC 5261 didn't specify the root element so this is fine for that

A later RFC 7351 does specify a root element to be "patch" and it would be nice if that was also supported.

Thanks in advance!

**Comment by jbuhacoff** [comment]
https://tools.ietf.org/html/rfc7351#section-2.1

**Comment by dnault** [comment]
Fixed in version 0.2.0, available now. Thanks for the report. Let me know if you run into any other difficulties.

**Comment by jbuhacoff** [comment]
Thanks for the quick response!!
Jonathan
