### ISSUE TITLE
outdated Gradle plugins and libs

### ISSUE THREAD

**Issue by nkiesel** [dnault/xml-patch#3]
Hi,

just started looking into this project and noticed that this is using an older gradle with older plugins and also 3rd party libs are not all current.  Interested in a pull request to fix these?  I also replaced all `import *` with qualified imports, and also have a migration to jdom2.

I am currently looking into the namespace modifications that are missing.  However, seems JDOM2 does not allow to go from a namespace identified via xpath to the parent element it's attached to.

**Comment by dnault** [comment]
Pull requests are most welcome. Thanks for taking the time to look at this.

**Comment by nkiesel** [comment]
created 2 pull requests.  I thought I'd be smart and make them independent, but I guess that was a bad idea as I'm pretty sure you will get merge conflicts if you try to merge both, as both modify `build.gradle`.  Should be easy to resolve though or else reject the 2nd request and I will rebase after you merged the first one.

**Comment by dnault** [comment]
Merged. Thank you :-)
