### ISSUE TITLE
Create standalone runnable JAR

### ISSUE THREAD

**Issue by maoo** [dnault/xml-patch#6]
Thanks for this lib, we're finding this very helpful (at Alfresco).

I just created a standalone JAR version in order to easily run it from commandline, you can check on https://github.com/Alfresco/xml-patch

Any chance this can be done directly via Gradle? Would you also be interested to push this JAR into Maven Central? It would make adopters life easier.

Thanks!
  mao

**Comment by dnault** [comment]
The newly released version 0.3.0 now has a standalone option. See "Getting the JAR" in the updated [README](https://github.com/dnault/xml-patch/blob/master/README.md) for details.

I'll tackle publication to Maven Central separately in issue #7.

Thanks for the suggestions!

**Comment by maoo** [comment]
Thanks @dnault , that's great! I'll give it a try!
